### PR TITLE
MCAS client: Add memory flush function to put_direct_offset

### PR DESCRIPTION
**Pull request by dickeycl**

### CODE REVIEW

**Comment by dickeycl** [comment]
Travis CI - Branch hung?

**Review by dwaddington — COMMENTED** [review]
Clem,
So if I understand this correctly, after a put_direct RDMA write is complete, the client does an RDMA send to send the OP_RELEASE_WITH_FLUSH message which performs the flush.  
Does this work with async_put_direct?

**Comment by dickeycl** [comment]
async_put_direct takes a write lock on a key. When the write lock is
removed, the put logic flushes the data, irrespective of whether it was
wrirten by a n fi_send or an fi_write. So that case was already covered.

**Comment by dwaddington** [comment]
[Flush persistent memory after RDMA writes](https://trello.com/c/BfCWMaYl/25-flush-persistent-memory-after-rdma-writes)

**Review by dwaddington — APPROVED** [review]

**Pull request merged**
