### PR TITLE
Moshik2

### PR DESCRIPTION
**Pull request by moshik1**
Add posterior_estimation example from HPEC 2021 paper: Non-Volatile Memory Accelerated Posterior Estimation

### CODE REVIEW

**Review by dwaddington — CHANGES_REQUESTED** [review]
Can we rename it to: examples/paper_examples/posterior_estimation_HPEC2021

**Comment by moshik1** [comment]
Renamed

**Review by dwaddington — CHANGES_REQUESTED** [review]
you still have papers_examples not paper_examples (better english ;-))

**Comment by moshik1** [comment]
renamed (I am hoping that we will have examples of more than one paper :-))

**Review by dwaddington — APPROVED** [review]

**Pull request merged**
