### PR TITLE
80: mm plugin with ccpm crash recovery

### PR DESCRIPTION
**Pull request by dickeycl**

### CODE REVIEW

**Comment by dickeycl** [comment]
Try to restart checks.

**Comment by dickeycl** [comment]
Restart

**Comment by dwaddington** [comment]
Spelling typos in comments...

/* Only reconsstitute support is in the constructor. */
/* initial cosntruction */
/* crach-consistent reconstitute */

**Comment by dwaddington** [comment]
I'm not sure about chaning the parameters on status_t mm_plugin_create(..) to have special params for persister and regions, callee_owns.  Can we generalize as a vector of pointers or something. If you are not supporting PMEM then these params are not needed.

**Comment by dickeycl** [comment]
Agree that the mm_plugin_create parameters are too specialized, but couldn't come up with a better solution. I don't think that an array (not vector, as this is a C interface) would be less specialized. It would bury the specialization one level deeper.

The intent for non-PMEM interfaces was that null pointers could be passed. This would have been the default except that, as a C interface, there are no defaults.

I will revisit this in a day or so.

**Review by dwaddington — APPROVED** [review]

**Pull request merged**
