### PR TITLE
8: initial access control for hstore "pools"

### PR DESCRIPTION
**Pull request by dickeycl**

### CODE REVIEW

**Comment by dwaddington** [comment]
@dickeycl  : I had a glance of this.  It is not quite what I expected since you seem to have put all of the logic in hstore as opposed to putting it in shard.cpp and using metadata storage of hstore/mapstore etc.  What was your intention with doing this in mapstore?
Can we raise the funcationality into the shard? (so we don't need to replicate mapstore, hstore etc. and any other store that comes along).
If you want to keep this design we can discuss and review with @moshik1 on Thu.

**Comment by dickeycl** [comment]
I did not put the code in shard because (a) I was thinking only of hstore and (b) I did not expect anyone to use this version. It has too many pitfalls. But I will move it to the shard side.

**Comment by dwaddington** [comment]
Thinking more on this, we should discuss Thu.  The advantage of putting in hstore/mapstore directly is that if we use those components directly (with the network), then we can still have access control.  Although the same effect might be possible with some thin layer that can be used outside of shard code.

**Comment by dickeycl** [comment]
I was in fact putting the shard changes in a thin layer, to avoid chasing down all current (and future) shard calls through the KVStore interface. It's true that putting the logic in hstore is a bit more secure, but hstore still depends on the shard layer not to forge the userid.

Troubles I found with either interface:
(1) functions which go through all keys (iterator, map)  can read or write all values, including ACL values. Have to make iterators smarter so they skip over (or disallow access to) keys depending on access to the particular key.
(2) the KVStore API can add function to get/set attributes methods of which a thin layer will not be aware. Thin layer needs to restrict get/set attributes to those attributes it recognizes lest a new attribute allow unwanted access.
(3) there is no access control outside pools. Anyone can call any function which does not take a pool handle.
(4) get_direct calls set a const void* pointer to data. A user without write privilege can const_cast that pointer to write the data.

**Comment by dwaddington** [comment]
Item to be handed over to me. More design required.

**Pull request closed without merging**
